fullnameOverride: hello-dev
appName: hello-dev
replicaCount: 1

image:
  repository: ghcr.io/kaybe005/hello-app
  tag: "5aa82e2d0963232882cd5916a19d484ee12a9850"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: traefik
  host: hello-dev.home.lab

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
